# Generated by Django 5.2.12 on 2026-09-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=120, verbose_name='نوع الرف / الوحدة')),
                ('unit', models.CharField(default='شهرياً', max_length=40, verbose_name='وحدة القياس')),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المعياري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سعر رف معياري',
                'verbose_name_plural': 'أسعار الأرفف المعيارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.CharField(max_length=30, unique=True, verbose_name='رقم المورد')),
                ('legal_name', models.CharField(max_length=200, verbose_name='الاسم القانوني')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم التجاري')),
                ('cr_number', models.CharField(blank=True, max_length=40, verbose_name='السجل التجاري')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('supply', 'توريد'), ('shelf_rent', 'إيجار أرفف'), ('marketing', 'تسويق'), ('services', 'خدمات')], max_length=20, verbose_name='نوع العقد')),
                ('subtype', models.CharField(blank=True, choices=[('fresh', 'فريش'), ('food', 'غذائي'), ('non_food', 'لا غذائي'), ('account_opening', 'فتح حساب')], max_length=30, verbose_name='النوع الفرعي')),
                ('internal_classification', models.CharField(blank=True, max_length=160, verbose_name='التصنيف الداخلي')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('notice_period_days', models.PositiveIntegerField(default=30, verbose_name='فترة الإشعار (يوم)')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة الفعلية')),
                ('has_non_standard_terms', models.BooleanField(default=False, verbose_name='شروط غير معيارية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('under_review', 'تحت المراجعة'), ('pending_approval', 'بانتظار الموافقة'), ('pending_signature', 'بانتظار التوقيع'), ('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], default='draft', max_length=24, verbose_name='الحالة')),
                ('both_parties_signed', models.BooleanField(default=False, verbose_name='توقيع الطرفين مكتمل')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال التوقيع')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('shelf_actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الرف الفعلي')),
                ('manually_escalated', models.BooleanField(default=False, verbose_name='تصعيد يدوي لإدارة العقود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_contracts', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول العقد التجاري')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounts.department', verbose_name='القسم المسؤول')),
                ('purchasing_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشتريات')),
                ('shelf_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.shelfrate', verbose_name='نوع الرف المعياري')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.vendor', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
                'permissions': [('approve_as_head', 'يمكنه الاعتماد كرئيس قسم'), ('approve_as_contracts_manager', 'يمكنه الاعتماد كإدارة عقود'), ('legal_review_contract', 'يمكنه المراجعة القانونية')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='الإجراء')),
                ('from_status', models.CharField(blank=True, max_length=24, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, max_length=24, verbose_name='إلى حالة')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('original', 'النسخة الأصلية'), ('signed', 'النسخة الموقعة'), ('addendum', 'ملحق'), ('renewal_letter', 'خطاب تجديد'), ('termination_letter', 'خطاب إنهاء'), ('other', 'أخرى')], default='original', max_length=24, verbose_name='النوع')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='الملف')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contracts.contract', verbose_name='العقد')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='وصف الهدف')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة الهدف')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الخصم %')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'هدف / شريحة خصم',
                'verbose_name_plural': 'أهداف الخصم',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('department_head', 'رئيس القسم'), ('contracts_manager', 'إدارة العقود'), ('legal', 'الشؤون القانونية')], max_length=32, verbose_name='جهة الاعتماد')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('decision', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('escalated', 'مصعّد')], default='pending', max_length=16, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('comment', models.TextField(blank=True, verbose_name='تعليق')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'خطوة موافقة',
                'verbose_name_plural': 'خطوات الموافقة',
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'role', 'sequence'), name='uniq_approval_step')],
            },
        ),
        migrations.CreateModel(
            name='ContractAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('expiry_90', 'انتهاء خلال 90 يوماً'), ('expiry_60', 'انتهاء خلال 60 يوماً'), ('expiry_30', 'انتهاء خلال 30 يوماً'), ('renewal_notice', 'آخر يوم للإشعار بعدم التجديد'), ('unsigned_approved', 'معتمد بدون توقيع'), ('expired_still_active', 'منتهٍ وما زال نشطاً'), ('shelf_price_deviation', 'انحراف سعر إيجار الأرفف')], max_length=32, verbose_name='نوع التنبيه')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('critical', 'حرج')], max_length=12, verbose_name='الحدة')),
                ('message', models.CharField(max_length=255, verbose_name='الرسالة')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_open', 'severity'], name='contracts_c_is_open_4baa1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'alert_type'), name='uniq_contract_alert_type')],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'end_date'], name='contracts_c_status_537325_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type', 'status'], name='contracts_c_contrac_fd43fa_idx'),
        ),
    ]
