# Generated by Django 5.2.12 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractattachment',
            name='kind',
            field=models.CharField(choices=[('original', 'النسخة الأصلية'), ('legal_review', 'نسخة المراجعة القانونية'), ('signed', 'النسخة الموقعة'), ('addendum', 'ملحق'), ('renewal_letter', 'خطاب تجديد'), ('termination_letter', 'خطاب إنهاء'), ('other', 'أخرى')], default='original', max_length=24, verbose_name='النوع'),
        ),
    ]
