# Generated by Django 5.2.12 on 2026-09-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contracts_officer', 'موظف قسم العقود'), ('purchasing_officer', 'موظف المشتريات'), ('purchasing_head', 'رئيس قسم المشتريات'), ('contracts_manager', 'مدير إدارة العقود'), ('legal', 'الشؤون القانونية'), ('admin', 'مدير النظام')], max_length=32, verbose_name='الدور')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='المسمى الوظيفي')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.department', verbose_name='القسم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
